### ISSUE TITLE
Node Creation Bug

### ISSUE THREAD

**Issue by jamilabreu** [neo4jrb/neo4j#761] opened 2015-04-19 01:03 UTC
When attempting to seed my db, I came across this bug:
```
ivy_league = Community.create(name: "Ivy League")

%W( Yale Harvard Cornell ).each do |name|
	School.create(name: name, child_of: [ivy_league])
end

School.create(name: "The College of New Jersey")
```
This will incorrectly mark "The College of New Jersey" node as a child of ivy_league, while creating that node first:

```
School.create(name: "The College of New Jersey")

ivy_league = Community.create(name: "Ivy League")

%W( Yale Harvard Cornell ).each do |name|
	School.create(name: name, child_of: [ivy_league])
end
```
produces the correct result.

**Comment by cheerfulstoic** [comment] 2015-04-19 21:02
Oh, wow, this is an interesting bug.  We'll definitely take a look, thanks!

**Comment by subvertallchris** [comment] 2015-04-19 21:17
If I'm reading it correctly [this](https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/property.rb#L14) is the culprit. It sets an `@_association_attributes` hash at the class level, `{association_name: target_obj}`, then it's keeping the value for all subsequent passes. I think I see a fix for it, I'll poke at it now.

**Comment by cheerfulstoic** [comment] 2015-04-19 22:01
Just pushed a fix.  Are you running off `master`?

**Comment by jamilabreu** [comment] 2015-04-20 00:44
Yep, running off master. Seems to be behaving differently now - though not as intended:

```
tcnj = School.create(name: 'The College of New Jersey')

ivy_league = Community.create(name: "Ivy League", slug: "ivy-league")

%W( Yale Harvard Cornell ).each do |name|
	School.create(name: name, slug: name.parameterize, child_of: [ivy_league])
end
```
The above now adds tcnj as a child of ivy_league three times: https://cloudup.com/cOHDuY7aqhN

While moving the creation of tcnj to the bottom creates 3 self-referential child_of relationships on ivy_league: https://cloudup.com/cEiHzjXY-d0

Odd :/

**Comment by subvertallchris** [comment] 2015-04-20 00:46
Damn it. I wonder if that is my fault. Can you lock your Gemfile at `gem 'neo4j', github: 'neo4jrb/neo4j', ref: '765ec93f37225049ddd88c959a95f237337e097e'` and tell me if it works?

**Comment by jamilabreu** [comment] 2015-04-20 00:53
Works :D

**Comment by subvertallchris** [comment] 2015-04-20 00:53
Hmm... That's no good. I'll have to add your example to Brian's tests and see if I can pin down what's causing it.

**Comment by jamilabreu** [comment] 2015-04-20 00:56
Oh no! I'm very new to neo4j, but ping me if I can help

**Comment by subvertallchris** [comment] 2015-04-20 00:58
Thank you! Using master, reporting issues, and following up with us is a huge help.

**Comment by jamilabreu** [comment] 2015-04-20 01:01
:smile: :+1:

**Comment by subvertallchris** [comment] 2015-04-20 01:13
Do you have a sec that you could pop into http://gitter.im/neo4jrb/neo4j? I can't reproduce this but might be overlooking something.

**Comment by subvertallchris** [comment] 2015-04-20 01:23
I'll be heading out for the night a few minutes but I'll be signed into Gitter all day tomorrow if you have a minute. In the meantime, try a `bundle update neo4j` with your gemfile not locked to that one commit. Nothing is jumping out at me that'd cause what you're reporting and I can't recreate it, so I wonder if it's just a weird glitch, but let's poke at it more to be sure.

**Comment by jamilabreu** [comment] 2015-04-20 03:57
I poked around a bit, ran ```brew update && brew upgrade``` (which installed a new neo4j homebrew package), created a rails app from scratch, and it seems to be working now. Will follow up tommorrow.

Though I did come across a few other quirks: https://github.com/neo4jrb/neo4j/issues/763 and https://github.com/neo4jrb/neo4j/issues/760

**Comment by jamilabreu** [comment] 2015-04-20 14:25
yep, looks like i was running neo4j 2.2.0 - all systems go on 2.2.1

**Comment by subvertallchris** [comment] 2015-04-20 14:43
I don't think it was a 2.2.0 issue, seems like other wires crossed somewhere. Glad it's all working, though! Was nervous there for a sec. ;-)

**Closed by subvertallchris** 2015-04-20 14:43 UTC
Labels: in progress
