### ISSUE TITLE
Neo4j::DeprecatedSchemaDefinitionError - Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database.

### ISSUE THREAD

**Issue by sebastialonso** [neo4jrb/neo4j#1356] opened 2017-02-13 20:44 UTC
Neo4j::DeprecatedSchemaDefinitionError:
                 Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database.  Run the following to create them:

* Happens when I run the specs on my Neo4j models. I'm working on a dockerized environment.
* RSpec works **fine** with any other ActiveRecord models.
* Connection to Neo4j dev container is **successful and without issues**
* Connection to Neo4j test conatiner is **successful and without issues**

Timeline:
1. Create Node model
~~~
rails g model Node node_id:integer label:string unique_identifier:string representation:integer power_index:float project_support:float
~~~~

It creates a migration, **which is different** that every video tutorial the official site has. Maybe is a new "feature"? I cannot longer work without migrations.
The model **also contains a serialized attributes which was not included in the cli command**

~~~
class Node 
  include Neo4j::ActiveNode
  property :node_id, type: Integer
  property :label, type: String
  property :unique_identifier, type: String
  property :representation, type: Integer
  property :power_index, type: Float
  property :project_support, type: Float
  
  property :categories
  serialize :categories
end
~~~

2. Create Node factory

~~~
FactoryGirl.define do
	sequence :unique_ident do |n|
		Faker::StarWars.quote.to_s + '#{n}'
	end
	factory :node do
		node_id { Faker::Number.number(3).to_i }
		label { Faker::StarWars.planet }
		unique_identifier { FactoryGirl.generate(:unique_ident) }
		representation { Faker::Number.number(1).to_i }
		categories { [1, 2, 3] }
		power_index { rand * 1 }
		project_support { rand * 1 }
	end
end
~~~

3. Run the rspec command

~~~
require 'rails_helper'

RSpec.describe Node, type: :model do
  describe "when creating" do
    let(:node) { FactoryGirl.create(:node) }
    it "it is valid" do
      expect(node.valid?).to be_truthy
    end
  end
end
~~~

and the famous error comes up

`docker-compose exec neo4j_rails_container **rspec spec/models/node_spec.rb**`

~~~
Failures:

  1) Node when creating it is valid
     Failure/Error: let(:node) { FactoryGirl.create(:node) }
     
     Neo4j::DeprecatedSchemaDefinitionError:
                 Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database.  Run the following to create them:
     
       rake neo4j:generate_schema_migration[constraint,Node,uuid]
     
     
       And then run `rake neo4j:migrate`
~~~

4. I run the migration

`docker-compose exec neo4j_rails_container **rake neo4j:migrate**`

~~~
== 20170213202544 ForceCreateNodeUuidConstraint: running... ====================
 CYPHER CREATE CONSTRAINT ON (n:`Node`) ASSERT n.`uuid` IS UNIQUE 
== 20170213202544 ForceCreateNodeUuidConstraint: migrated (0.3480s) ============
~~~

5. Run the specs again, same error.

The errors appears when the factory instance is created, so there's something wrong with the model.
Please, any idea on what I'm doing wrong is greatly appreciated.
### Runtime information:

Neo4j database version: 3.1 or rather lastest (as it's pulled from [Docker Registry](https://hub.docker.com/_/neo4j/) )
`neo4j` gem version: 8.0.6
`neo4j-core` gem version: 7.0.3

**Comment by Joshfindit** [comment] 2017-02-15 00:41
8.0 introduced migrations (see [here](http://neo4jrb.readthedocs.io/en/8.0.x/UniqueIDs.html?highlight=migration#a-note-regarding-constraints) and [here](http://neo4jrb.readthedocs.io/en/8.0.x/Migrations.html#migrations))

Besides that, is this related to https://github.com/neo4jrb/neo4j/issues/1330 ?

**Comment by sebastialonso** [comment] 2017-02-15 20:07
Hi @Joshfindit. It's not really related I believe, since I can run the migrations and the command exists.

I have run the migrations, as I have pasted the log result above, but when the factory tries to create a Node I'm left with the error. The questions I'm constantly asking myself with this are 
* Does the factory needs an **uuid**?
* Do I need to add every model property to the migration? (this seems confusing, since Neo4j is a schema-less db)

**Comment by cheerfulstoic** [comment] 2017-02-16 02:20
First I would suggest checking out the upgrade guide:

http://neo4jrb.readthedocs.io/en/8.0.x/UpgradeGuide.html

There are a couple of big changes that we made in version 8.0 of the `neo4j` gem.  The biggest one that you're running into is that it is no longer possible to specify the database schema (in Neo4j the schema is just indexes and constraints) in the model and have the schema created automatically at runtime.  This is because the magical behavior caused various headaches and migrations are a more deliberate mechanism for changes to the database.

In `ActiveNode`, all models have an `id_property`.  If you don't specify one this will be the `uuid` property by default.

You don't need to create/specify any properties in the database because, as you say, Neo4j is schemaless (at least with regards to properties/labels/relationships).  The gem **does** however require that there be a Neo4j uniqueness constraint on the `id_property` for any model.  This is so that the database can enforce the uniqueness of the `id_property` and so that queries for the `id_property` can be efficient (since uniqueness constraints on a label/property come automagically with an index)

We would like to have something akin to `ActiveRecord`'s `schema.rb` file so that you don't need to run all migrations to get the schema setup (especially for tests).  This does not currently exist, unfortunately.

Also, an important thing to note is that if you're running tests you may need to specify `RAILS_ENV=test` when running `rake db:migrate` to make sure the migrations run on your test DB rather than your development DB.

Hopefully that answers your questions!  I'm going to close this issue because I don't *think* there's anything to be done, but I'm happy to continue the conversation here or re-open if there is something to do/fix

**Closed by cheerfulstoic** 2017-02-16 02:20 UTC

**Comment by sebastialonso** [comment] 2017-02-16 12:32
Excellent explanation! Thank you very much.

I'd like to add for any future time travelers, that the `Neo4j::DeprecatedSchemaDefinitionError` error it most likely has to do with a **pending migration**. Check the status of migrations (in every environment just to be sure, that was my mistake) with `rake neo4j:migrate:status` to avoid any confusion.

**Comment by cheerfulstoic** [comment] 2017-02-16 22:24
As a clarification, `DeprecatedSchemaDefinitionError` could mean that you haven't run migrations, or it could mean that you need to create migrations (which you then need to subsequently run).

**Comment by KapilMetacube** [comment] 2017-12-10 07:35
Hi @cheerfulstoic,
I have upgraded from 4.3 to version 8.3 now and getting the below error on circleci while running test cases (using rspec)
_Note: All errors are against `id_property`_
```ruby
Neo4j::DeprecatedSchemaDefinitionError:
                 Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database.  Run the following to create them if you haven't already:
       rake neo4j:generate_schema_migration[constraint,<class1>,id]
       rake neo4j:generate_schema_migration[constraint,<class2>,id]
       rake neo4j:generate_schema_migration[constraint,<class3>,id]
       rake neo4j:generate_schema_migration[constraint,<class4>,id]

```
I have written migrations for adding both index and constraints and still encountering the above issue.
Before adding migration it was showing the error for 6 elements (and now 4) the other two being 

```ruby
       rake neo4j:generate_schema_migration[constraint,<class1>,entity_id]
       rake neo4j:generate_schema_migration[constraint,<class2>,entity_id]
```
Please note that `entity_id` is not an id_property while `id` (for which issue is still existing) is `id_property` of the model.

Also, note that I'm using version `2.3.4` of the neo4j database and thus is also getting a warning about `neo4j schema:dump`, `WARNING: This task does not work for versions of Neo4j before 3.0.0`

Is this related to my neo4j DB version being less than 3.0.0 or something else?
Or I have to override circleci.yml to run `rake neo4j:migrate` as `schema:dump` will not run, the version being less than 3.0.0

Please help as my test cases are working fine on my local/development machine but are failing on circleci.

**Comment by thefliik** [comment] 2017-12-10 15:14
@KapilMetacube, and in addition to running migrations to create the appropriate constraints, you removed any references to `:index` / constraints from your ActiveNode models, correct?

**Comment by cheerfulstoic** [comment] 2017-12-10 15:48
Hey @KapilMetacube 

For the errors about creating migrations, were the `id` properties defined as your `id_property` on your models?  I ask because the default is `uuid`.

So you say it was showing the error for 6 and now it's just four?  Is there something different about the two which aren't showing anymore?

One thing to check also is that `constraint` and `index` options on `property` model definitions are no longer supported, so if you have those you might be getting issues.  Be sure to check out the [upgrade guide](http://neo4jrb.readthedocs.io/en/9.1.x/UpgradeGuide.html) and specifically the [indexes and constraints](neo4jrb.readthedocs.io/en/9.1.x/UpgradeGuide.html#indexes-and-constraints) section.

If none of that is helpful perhaps you could share privately a model which you are having trouble with.

Regarding the `schema:dump` rake task, that is because the `schema:dump` and `schema:load` tasks make a Cypher call to `CALL db.indexes()` which is only supported in version 3.0 of Neo4j.  The `schema:*` tasks are something that you can get by without (they manage the `schema.yml` file which is used to quickly create test databases or new production databases quickly without running through all of the migrations).  If you aren't using 3.0 those tasks simply won't do anything (though `schema:dump` is run automagically whenever you run `neo4j:migrate`)

**Comment by KapilMetacube** [comment] 2017-12-11 06:18
Hi @cheerfulstoic,
I have gone through the guides before upgrading (we have also discussed that in another issue).
Yes, `id` is `id_property` in my models (not using default `uuid` ). _I also tried to convey that via a Note_

After upgrading I was getting the warning about index and constraints on model definitions.
So I removed them from model definitions and created a migration to add all `indexes` and `constraints`.

After running the migration, warnings were not there except `WARNING: This task does not work for versions of Neo4j before 3.0.0`, which would not be an issue as per your comment (as I understand).

The two elements (`entity_id`) that were not showing up error after running the migrations were not `id_property`, that's what different about them.

Example model:

```ruby
class Graph::Node::ChainNode
  include Neo4j::ActiveNode
  property :name, type: String
  property :entity_id, type: Integer, constraint: :unique  # NOTE: constraint: :unique was removed after upgrading. Shown here just for reference

  id_property :id, on: :primary_key
  validates :name, :entity_id, presence: true

  def primary_key
    entity_uuid
  end

  def self.typesafe_accessor(name, type)
    define_method(name) do
      instance_variable_get("@#{name}")
    end

    define_method("#{name}=") do |value|
      if value.is_a? type
        instance_variable_set("@#{name}", value)
      else
        raise ArgumentError, 'Invalid Type'
      end
    end
  end
  typesafe_accessor :entity_uuid, String
  ...
end
```

Please note that constraint was there before only on `entity_id` and not on `id` (`id_property`). However, as the [guide ](http://neo4jrb.readthedocs.io/en/9.1.x/UniqueIDs.html#a-note-regarding-constraints) suggests, there MUST be a constraint on `id_property`.

Was this helpful, did you get an idea of whats happening?
Thanks

**Comment by KapilMetacube** [comment] 2017-12-12 11:46
Hi @cheerfulstoic,
This time I tried to add a pre block to the circle.yml to execute neo4j migration in Test Environment on circleci. 

```yml
test:
  pre:
  - bundle exec rake neo4j:migrate --trace:
      environment:
        RAILS_ENV: test
        RACK_ENV: test
```
The migrations did run (output shown below)

```ruby
export RAILS_ENV="test"
export RACK_ENV="test"
bundle exec rake neo4j:migrate --trace
** Invoke neo4j:migrate (first_time)
** Execute neo4j:migrate
** Invoke neo4j:migrate:all (first_time)
** Invoke neo4j:allow_migrations (first_time)
** Execute neo4j:allow_migrations
** Invoke environment (first_time)
** Execute environment
** Execute neo4j:migrate:all
== 20171208054250 AddAllIndexes: running... ====================================
 CYPHER CREATE INDEX ON :`Graph::Node::ChainNode`(name) 
 CYPHER CREATE INDEX ON :`Graph::Node::ChainNode`(city) 
 CYPHER CREATE INDEX ON :`Graph::Node::ChainNode`(state) 
 CYPHER CREATE INDEX ON :`Graph::Node::ChainNode`(country) 
 CYPHER CREATE INDEX ON :`Graph::Node::ServiceNode`(name) 
 CYPHER CREATE INDEX ON :`Graph::Node::ProductNode`(name) 
 CYPHER CREATE INDEX ON :`Graph::Node::EntityNode`(name) 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::ChainNode`) ASSERT n.`id` IS UNIQUE 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::EntityNode`) ASSERT n.`id` IS UNIQUE 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::ProductNode`) ASSERT n.`id` IS UNIQUE 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::ProductNode`) ASSERT n.`entity_id` IS UNIQUE 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::ServiceNode`) ASSERT n.`id` IS UNIQUE 
 CYPHER CREATE CONSTRAINT ON (n:`Graph::Node::ServiceNode`) ASSERT n.`entity_id` IS UNIQUE 
== 20171208054250 AddAllIndexes: migrated (1.3262s) ============================

** Invoke neo4j:schema:dump (first_time)
** Invoke environment 
** Execute neo4j:schema:dump
WARNING: This task does not work for versions of Neo4j before 3.0.0
```

But I'm still getting the same error.
Am I missing something here?

**Comment by cheerfulstoic** [comment] 2017-12-12 13:27
I'm assuming you're talking about the "Some schema elements were defined by the model" error rather than the `WARNING`.

I'm not sure why you would be getting that error if you have the right constraints in the DB.  If you look at the schema (you can run `:schema` in the web query console), did those constraints all get created correctly in the correct database?  If that's the case and if the server has been restarted since you ran the migrations, then it could perhaps be a bug with `id_property` properties which aren't `uuid`

**Comment by KapilMetacube** [comment] 2017-12-12 16:27
Your assumption is right, I'm talking about the error `Neo4j::DeprecatedSchemaDefinitionError`.
I ran `:schema` and is able to see all the indexes and constraints on the database.
And I even restarted the database.

Might be the case you are speculating... as non-`id_property` properties are not showing the error.
Thanks for the help.
What's next?

**Comment by thefliik** [comment] 2017-12-12 18:50
Hmm, the fact that everything's working fine on your development machine, and you're just running into issues in the circleci environment, would lead me to guess that something's not being configured correctly for circleci. 

It's quite possible you've already tried this, but what I've done to try and diagnose some hard problems is to create a new application which just replicates the minimum necessary to seemingly recreate the problem. If it is a bug with the `id_property`, you should be able to share this test app and help fix it. If it's a problem with the setup, that should also help.

**Comment by KapilMetacube** [comment] 2017-12-15 06:48
@thefliik @cheerfulstoic The issue is resolved now.
The problem was with the SchemaMigration node getting deleted.
```ruby
  config.before(:suite) do
    query = 'MATCH (n) OPTIONAL MATCH (n)-[r]-() DELETE n,r'
    Neo4j::ActiveBase.current_session.query(query).to_a
  end
```
Reviewing the [guide](http://neo4jrb.readthedocs.io/en/8.0.x/Miscellany.html#cleaning-your-database-for-testing) helped me in the track again.

Now, excluding SchemaMigration node by
```ruby
  config.before(:suite) do
    query = 'MATCH (n) WHERE NOT (n:`Neo4j::Migrations::SchemaMigration`) OPTIONAL MATCH (n)-[r]-() DELETE n,r'
    Neo4j::ActiveBase.current_session.query(query).to_a
  end
```
fixed it.

However, I still don't understand why the tests were not failing on my development machine.
Will see to it though.
Thanks for all the help.

**Comment by cheerfulstoic** [comment] 2017-12-15 13:52
Excellent, thanks for the update!

**Comment by KapilMetacube** [comment] 2017-12-15 16:15
@cheerfulstoic @thefliik, 
As I was figuring out why it was passing on the development machine and not on circleci, below is the explanation of what I found out **until now**.
Development machine executes test cases in a single container, while on circleci was we are using 3X container parallelism. And this is where the problem lies.
And this is why my previous comments state that my test cases passed, though I changed the way how database cleaner was working, I also override the test command for executing the specs(the app uses rspec) which ran on a single container on circleci, rather than 3.
And as soon as I changed back the test cases to use parallelism the test cases broke.

So I'm again where I started, as parallelism is must because of the time factor.
This also means that the query `MATCH (n) WHERE NOT (n:`Neo4j::Migrations::SchemaMigration`) OPTIONAL MATCH (n)-[r]-() DELETE n,r` **might** not be causing the problem here.

I have raised a [bug report](https://discuss.circleci.com/t/test-cases-fails-if-parallelism-is-used-passes-otherwise/18828) on circleci.
Hope it gets resolved soon.
Thanks

**Comment by cheerfulstoic** [comment] 2017-12-15 17:38
I guess I'm curious to know how the parallelism works.  Are there three separate Ruby processes connecting to three separate Neo4j DBs?  It's been a while since I've used Circle CI.  Maybe I'll wait for the response from them, first...

**Comment by KapilMetacube** [comment] 2018-01-02 05:58
@cheerfulstoic @thefliik The issue was resolved by adding `parallel: true` flag to the `rake neo4j:migrate` command in `circleci.yml`.
In a way, circleci UI adds confusion as this command was shown running on all the container as looking at the UI but actually ran only on the first container and not on other containers.

Thanks for all the help

**Comment by cheerfulstoic** [comment] 2018-01-06 14:58
Ah, good to know, thanks!
