### ISSUE TITLE
initialize / find callbacks do not work

### ISSUE THREAD

**Issue by garmoshka-mo** [neo4jrb/neo4j#723] opened 2015-03-19 22:10 UTC
As described here: https://github.com/neo4jrb/neo4j/wiki/Neo4j%3A%3AActiveNode#callbacks
i expect to have callbacks working, though those do not work:

tried different variations:
````
after_initialize
initialize
before_initialize
before_find
find
after_find
````

Some of callbacks work, for example those:

* before_validation / after_validation
* before_create / after_create
* before_save / after_save

Checked by this code:

````
class Te
    include Neo4j::ActiveNode
    property :name

    before_validation do
      print 'before_validation callback'
    end

    after_validation do
      print 'after_validation callback'
    end

  before_initialize do
    print 'before_initialize callback'
  end

  after_initialize do
    print 'after_initialize callback'
  end

end

    n = Te.create(name: '999')
    n.name = 'xxxx'
    n.save
    n.update name: 'yyyyy'
    Te.find_by name: 'xxxx'

````

Moreover, when you try to catch after_find / before_find callbacks - 
other callbacks which worked in class before - also stop working.

E.g. here - validation not working anymore:
````
class Te

    include Neo4j::ActiveNode
    property :name

    after_find do
      print 'after_find callback'
    end

    before_find do
      print 'before_find callback'
    end

    before_validation do
      print 'before_validation callback'
    end

    after_validation do
      print 'after_validation callback'
    end

end
````

The last behavior confuses a lot

**Comment by subvertallchris** [comment] 2015-03-19 22:16
So the act of including the `find` callbacks cause the `validation` callbacks to stop working?

**Comment by garmoshka-mo** [comment] 2015-03-19 22:20
Yes, if they are included before validation callbacks.

But the most sad thing, is that initialize/find callbacks do not work at all

**Comment by garmoshka-mo** [comment] 2015-03-19 22:28
Maybe it simply was never implemented...

![screen shot 2015-03-19 at 4 17 49 pm](https://cloud.githubusercontent.com/assets/2452269/6742363/d134a6f4-ce54-11e4-9da8-7770e95ab44e.png)

Don't know how it should work, but looks like that
Need at least fix documentation then

**Comment by subvertallchris** [comment] 2015-03-20 23:36
I imagine we'd need a `run_callbacks(:find)` in there? I didn't implement any of those so I'm not entirely sure how all the callbacks are implemented. We should add a failing test and work from there.

**Comment by subvertallchris** [comment] 2015-10-21 21:37
Someone else reported that `after_initialize` callbacks were not firing and I seem to have confirmed. It looks like only some of those callback methods were ever expected to work:

```
define_model_callbacks :initialize, :find, only: :after
define_model_callbacks :save, :create, :update, :destroy
```
But the act of actually triggering _any_ callbacks seems to be a side-effect of other methods implemented in the gem, as you pointed out in that screenshot. If we follow the pattern in use, the solution is to define the methods that expect to trigger callbacks and run them manually. I'm going to write some failing tests for this and see if I can correct it.

**Comment by subvertallchris** [comment] 2016-01-17 02:24
This was fixed a few months back so I'm closing. Thanks for reporting!

**Closed by subvertallchris** 2016-01-17 02:24 UTC
Labels: next release
