### ISSUE TITLE
Block Notation Bug

### ISSUE THREAD

**Issue by jamilabreu** [neo4jrb/neo4j#760] opened 2015-04-18 19:13 UTC
Just a heads up: declaring relationships is broken when creating objects using block notation:

UPDATED:
```
Community.create! do |community|
	community.name = "Yale"
	community.part_of = ivy_league
end
```
Yields a community with no part_of relationship, while this works as expected:

```
Community.create!(name: "Yale", part_of: ivy_league)
```

**Comment by subvertallchris** [comment] 2015-04-30 18:08
To be honest, I don't know if this is going to get fixed without some real magic, and  I don't think that it'd be worth it. The problem is with how the mixing of declared props and association methods plays out during persistence:

```
      def create(props = {})
        association_props = extract_association_attributes!(props) || {}

        new(props).tap do |obj|
          yield obj if block_given?
          obj.save
          association_props.each do |prop, value|
            obj.send("#{prop}=", value)
          end
        end
      end
```
Normally, it takes the hash given, pulls out the associations, saves the node, then creates the relationships. When you give a block, you're calling methods on a non-persisted node object, so `node.association = other_node` won't have the expected result, and we have no way of getting the list of pending association creations since no such thing exists.

If we make the discussed change that would allow you to call association setters on non-persisted nodes that don't take effect until `save` is called, then this would be doable. In the meantime, my advice is to avoid this.

**Comment by subvertallchris** [comment] 2016-01-17 02:49
Was going through old issues and realized that this was corrected when we added support for rel creation between unpersisted nodes! I added a passing spec, https://github.com/neo4jrb/neo4j/commit/efc24d5373651b69d6a5582d86ab8aa77a0e4a31, to prove and ensure that we don't somehow lose this behavior in the future.

**Closed by subvertallchris** 2016-01-17 02:49 UTC
