### ISSUE TITLE
Lost Genuine ActiveNode Inheritance for SuperClass Relationships

### ISSUE THREAD

**Issue by Tanninator** [neo4jrb/neo4j#1380] opened 2017-05-03 21:12 UTC
I noticed that with the new Neo4j version in the 8.*, the gem seems to no longer support ActiveNode inheritance for the relationships of a SuperClass.

For example:
```
class A
     include Neo4j::ActiveNode
     has_many :out, :contains, type: :a_contains_b, model_class: 'B'
end

class B
     include Neo4j::ActiveNode
     has_one :in, :contained, type: :a_contains_b, model_class: 'A'
end

class C < A
end

class D < A
end
```
In this example, trying to run rspec spec results in the error: 
`RuntimeError: Association 'contains' defined for a second time. Associations can only be defined once (Class#contains)`

This is because Neo4j:ActiveNode inheritance in the new ruby 8.* seems to only add on the extra label to the subclasses rather than the subclasses actually inheriting the relationship from the superclass. And so, when loading the models, it thinks that we're adding :contains twice to the same node. 

I ask because I want to be able to use classes like D and C to duck type calls for their superclass, as well as be able to override their superclass relationships with their own relationships that can be used. Something like:

```
class Human
     include Neo4j::ActiveNode
     has_many :out, :birds, type: :bird_owner, model_class: 'Bird'
end

class Bird
     include Neo4j::ActiveNode
     has_many :out, :nests, type: :bird_nests_at, model_class: 'Nest'
     has_one :out, :owner, type: :bird_owner, model_class: 'Human'
end

class Nest
     include Neo4j::ActiveNode
     has_one :in, :bird, type: :bird_nests_at, model_class: 'Bird'
end

class Sparrow < Bird
     has_many :out, :nests, type: :bird_nests_at, model_class: 'TreeNest'
end

class BurrowingOwl < Bird
     has_many :out, :nests, type: :bird_nests_at, model_class: 'BurrowNest'
end

class TreeNest < Nest
     has_one :in, :bird, type: :bird_nests_at, model_class: 'Sparrow'
end

class BurrowNest < Nest
     has_one :in, :bird, type: :bird_nests_at, model_class: 'BurrowingOwl'
end
```
Where Bird and Nest classes are more like interfaces or inherited superclasses that don't have instances of their own but where the subclasses (Sparrow, BurrowingOwl) can inherit the :owner relationship from the superclass Bird and also override the :nest relationship with their own relationships. And that there could be Humans who can have :birds relationship that contains both kinds of birds (Sparrow and BurrowingOwl).

This is without making the model_class: [:Sparrow, :BurrowingOwl] of the Human#birds relationship--because I would also want to be able to string the associations. Like:

`Human.find_by(name: 'John').birds.nest` which would return a list of TreeNest's and BurrowNests.

This functionality works in version 7.2.0, but not in the current one, and I was wondering if anyone would restore this functionality.

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.15
`neo4j-core` gem version: 7.0.8

**Comment by cheerfulstoic** [comment] 2017-05-04 02:23
This was put in because people would define multiple associations with the same name in the same model (not inheriting) and it caused confusion.  We could perhaps only verify this duplication on the same classes, thus allowing inheritance, but I have a few of questions:

In your examples the `nests` and `bird` associations are always being overwritten, thus the parent class' association is never actually used.  So wouldn't it make sense to just define the associations on the child models?

That said, I completely understand the desire to be able to have the ability to define an association in a parent model and overwrite it for specific models, I just am not convinced by examples

Also, do models like `Sparrow` and `BurrowingOwl` have different behavior in the models?  If not then it probably makes more sense to store some sort of `type` relationship (even if they did have behavior, so long as it's not a significant difference I would probably start with a property on the model which defines the behavior).  **UPDATE AFTER LOOKING MORE** I wonder if it would make sense to have an `ActiveRel` model which enforces that you don't create a relationship between, for example, a `Sparrow` and a `BurrowNest`.  That way you could do things via checking properties on the models and you wouldn't have to create a large (and potentially growing) hierarchy of classes.

As a separate note, I don't know if these are examples, but your `type` options seem to have variable / method references rather than a symbol or a string, so I wouldn't expect them to work.  For example:

```ruby
class BurrowNest < Nest
     has_one :in, :bird, type: bird_nests_at, model_class: 'BurrowingOwl' # would not expect this to work
     has_one :in, :bird, type: :bird_nests_at, model_class: 'BurrowingOwl' # should work
     has_one :in, :bird, type: :bird_nests_at, model_class: :BurrowingOwl # I also recommend symbols for the `model_class`
end
```

**Comment by Tanninator** [comment] 2017-05-04 06:50
About the types needing to be symbols, you're right: that was an original typo that I copied over multiple times and didn't catch. I've updated the original post.

The associations are always being overwritten, but they're put in the parent model instead of the child model because I would like to string associations from outside the Child < Parent pair.

In the example given, it would be:
`Human.first.bird.nest`

If the Bird parent class lacks the association :nest, the ruby call returns an error saying that QueryProxy does not have method named, 'nest'. I'm guessing it's because the associations are lazy loaded by the class of the relationship given to the Human. If I make the method_class for Human#birds to be [:Sparrow, :BurrowingOwl], I run into the same error--probably because the query doesn't know to load the associations in each possible class.

Would creating an ActiveRel and checking the classes of the models on either side still allow for association chaining?

I'm working with classes and views that can chain associations pretty long. Like if I had a class called BirdOwnersAssociation with a list of members of class Human, it could be:
BirdOwnersAssociation.first.members.birds.nest

Sparrow and BurrowingOwl have very different behaviors in the way that they are handled with other functions and have very different properties, if that's what you're asking.

**Comment by cheerfulstoic** [comment] 2017-05-05 18:36
All fair enough ;)

I just started looking into this and realized we are already supposed to be testing this, but something must be wrong:

https://github.com/neo4jrb/neo4j/blob/873e4dbf8c0665ccca2ed0dd2b3b23217d5798cf/spec/e2e/has_many_spec.rb#L590

Looking deeper now

**Comment by Tanninator** [comment] 2017-05-05 18:42
Wooo!!! Thank you!! :) I'm really excited for this change, hahaha

**Comment by cheerfulstoic** [comment] 2017-05-05 18:46
I'm trying this locally and I'm not able to reproduce it...  Do you think you might be loading your models multiple times?  You might try putting a `puts` statement above the association where you're getting the error to verify that (and if so, you could also do `puts` called to see the backtrace of each time that it's loaded)

**Comment by Tanninator** [comment] 2017-05-05 19:03
Hmmm.

I went into the code and put in a debugger and a puts statement. It is loading the subclass models multiple times.

It's happening because...to run rspec, we do:
```
Dir["#{Rails.root}/app/models/**/*.rb"].each do |model|
  load model
end
```
And when it gets to the subclass (like, `Sparrow`), it loads the superclass as well. And so, by the time that it gets to time to load the actual superclass, I guess it's already been loaded and so the error comes up.
`Association `commits` defined for a second time. Associations can only be defined once (Class#commits) (RuntimeError)`

**Comment by cheerfulstoic** [comment] 2017-05-05 19:10
What if you change `load model` to `require model`?

**Comment by kroyagis** [comment] 2017-05-05 19:49
I'm running into a similar issue. I have no inheritance between my models, but after upgrading to neo4j 8.0.0, when I run `rake spec` I get the `/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/neo4j-8.0.17/lib/neo4j/active_node/has_n.rb:547:in 'rescue in build_association': Association 'profile' defined for a second time. Associations can only be defined once (Class#profile) (RuntimeError)`

My User and Profile models look like this:
```
class User
  include Neo4j::ActiveNode
  has_one :out, :profile, type: :has_profile
end

class Profile
  include Neo4j::ActiveNode
  has_one :both, :user, type: :has_profile
end
```

The whole error looks like:
```
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/neo4j-8.0.17/lib/neo4j/active_node/has_n.rb:547:in `rescue in build_association': Association `profile` defined for a second time. Associations can only be defined once (Class#profile) (RuntimeError)
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/neo4j-8.0.17/lib/neo4j/active_node/has_n.rb:536:in `build_association'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/neo4j-8.0.17/lib/neo4j/active_node/has_n.rb:369:in `has_one'
	from /Users/jiyou/Desktop/tilr/tilr-api/app/models/user.rb:5:in `<class:User>'
	from /Users/jiyou/Desktop/tilr/tilr-api/app/models/user.rb:1:in `<top (required)>'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:52:in `block (2 levels) in <top (required)>'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:51:in `each'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:51:in `block in <top (required)>'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:47:in `<top (required)>'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `require'
	from /Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `<top (required)>'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
```
I wrote ` puts 'about to defined profile at this point:', caller` before the `has_one` line, and the caller is:
```
about to defined profile at this point:
/Users/jiyou/Desktop/tilr/tilr-api/app/models/user.rb:1:in `<top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:212:in `const_missing_from_s3_library'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `const_get'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `inject'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `constantize'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:566:in `get'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:597:in `constantize'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise.rb:291:in `get'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/mapping.rb:81:in `to'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/mapping.rb:76:in `modules'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/mapping.rb:93:in `routes'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/mapping.rb:160:in `default_used_route'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/mapping.rb:70:in `initialize'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise.rb:325:in `new'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise.rb:325:in `add_mapping'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:238:in `block in devise_for'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:237:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.10/lib/devise/rails/routes.rb:237:in `devise_for'
/Users/jiyou/Desktop/tilr/tilr-api/config/routes.rb:6:in `block in <top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
/Users/jiyou/Desktop/tilr/tilr-api/config/routes.rb:3:in `<top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/Users/jiyou/Desktop/tilr/tilr-api/config/environment.rb:15:in `<top (required)>'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:14:in `require'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:14:in `<top (required)>'
/Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `require'
/Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `<top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
Running via Spring preloader in process 83866
about to defined profile at this point:
/Users/jiyou/Desktop/tilr/tilr-api/app/models/user.rb:1:in `<top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:51:in `block (2 levels) in <top (required)>'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:50:in `each'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:50:in `block in <top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
/Users/jiyou/Desktop/tilr/tilr-api/spec/rails_helper.rb:46:in `<top (required)>'
/Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `require'
/Users/jiyou/Desktop/tilr/tilr-api/spec/spec_helper.rb:21:in `<top (required)>'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
/Users/jiyou/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
```

**Comment by kroyagis** [comment] 2017-05-05 19:57
Above disappeared when I changed it to `require model`, thanks!

**Comment by cheerfulstoic** [comment] 2017-05-05 20:00
Thanks for checking that.

I wonder, does the problem go away if you change it back to `load model` and use an earlier version of 8.0.x (say, just 8.0.0).  It seems like more people would have experienced this, and if so, it's probably a more recent change to the 8.0.x series, so it might be possible to pin it down by changing your `Gemfile` to refer to specific versions and running `bundle update neo4j`.  Using a binary search between 8.0.0 and 8.0.17 should take less than six steps

**Comment by Tanninator** [comment] 2017-05-05 20:54
Hmm! It did disappear after switching it to require model. I'll try to pin down which version it was for you.

**Comment by kroyagis** [comment] 2017-05-05 20:54
I just downgraded to `gem "neo4j", '8.0.0'`, and change back to `load model`, and the problem came back :(

**Comment by cheerfulstoic** [comment] 2017-05-05 21:35
Thanks for checking!  Unfortunately that means it does seem to be something introduced in 8.0.x, which can really only be narrowed down to [this](https://github.com/neo4jrb/neo4j/compare/v7.2.3...v8.0.0).

So that we have as much data as possible, what was the exact version of 7.x that y'all were using before?

**Comment by Tanninator** [comment] 2017-05-05 21:44
I was running 7.2.0

**Comment by Tanninator** [comment] 2017-05-05 22:08
It's not a big deal for me though. `require model` works just as well for me as `load model`

**Comment by cheerfulstoic** [comment] 2017-05-06 00:32
Cool :+1:  My concern was for other people coming along later having the issue.  I'm actually curious about the bit of code:

```ruby
Dir["#{Rails.root}/app/models/**/*.rb"].each do |model|
  load model
end
```

Is that from a default generated template or maybe from a common bit of code shared online?

**Comment by Tanninator** [comment] 2017-05-07 01:32
To be honest, I'm not actually sure. I think that it is part of the default generated template from rspec, or it could just be a piece of legacy code that I'm not sure when it was introduced into the project.

**Comment by kroyagis** [comment] 2017-05-08 13:56
I was using 7.1.0

**Comment by cheerfulstoic** [comment] 2017-05-08 14:50
Thanks to both of you for all the feedback!  I'll close this issue for now, but I'd appreciate hearing from anybody else who has this issue

**Closed by cheerfulstoic** 2017-05-08 14:50 UTC
