### ISSUE TITLE
too many connection resets (due to end of file reached - EOFError) after 2902 requests on 62417760, last used 3.015954763 seconds ago

### ISSUE THREAD

**Issue by djvs** [neo4jrb/neo4j#716] opened 2015-03-12 03:29 UTC
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1413:in `block in transport_request'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1410:in `catch'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1410:in `transport_request'
     /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1383:in `request'

Probably self-explanatory, dies under some massive load.

**Comment by subvertallchris** [comment] 2015-03-12 04:12
I've run into this only a few times but can never consistently reproduce
it. Any chance you have an idea of what's causing it other than heavy load?

**Comment by djvs** [comment] 2015-03-12 04:17
It's connecting to localhost, so, no.

**Comment by djvs** [comment] 2015-03-12 04:18
Hit it 2 or 3 times so far after a few thousand queries (probably at least 7,000).

**Comment by subvertallchris** [comment] 2015-03-12 05:04
Can you give examples of some of your queries? Single active connection or
multiple concurrent sessions?

**Comment by djvs** [comment] 2015-03-12 05:06
Importing tons of models from an array of hashes, in this case.

**Comment by subvertallchris** [comment] 2015-03-12 05:07
With code that looks like...? ;-)

**Comment by subvertallchris** [comment] 2015-03-12 05:10
Also, enable `eager_load` in your environment if you're using Rails
and haven't already. It's known to prevent an error related to loading
models within transactions, though I'm not sure it's this one.

**Comment by djvs** [comment] 2015-03-12 05:15
It is using eager load at the beginning of the script.  All the code does is basically just make a model, save it, update it with some attributes, save it again, attach some associations.

**Comment by sahin** [comment] 2015-03-30 06:04
@subvertallchris hi,

I started to use neo4j fully again. I have hundreds of 

"Faraday::TimeoutError: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 1 requests on 69964643464320, last used 121.344128 seconds ago'

the logs are like that. 
````

2015-03-30 06:04:30 +0000 severity=INFO, CYPHER 4097ms MATCH (n1:`User`), (n2:`MovieOther`) WHERE (n1.uuid = {from_node_id}) AND (n2.uuid = {to_node_id}) CREATE (n1)-[r:`relates_movie`]->(n2) WITH r SET r.`relation_type` = {setter_r_relation_type}, r.`source` = {setter_r_source} RETURN r | {:from_node_id=>"b7763aa5-1949-4bce-98ee-8b475e1870a1", :to_node_id=>"c977be2c-3356-40cc-b427-fde2aa83aa70", :setter_r_relation_type=>"watched", :setter_r_source=>"facebook"}
2015-03-30 06:04:38 +0000 severity=INFO, CYPHER 19ms MATCH (n:`User`) WHERE (n.mongo_id = {n_mongo_id}) RETURN n LIMIT {limit_1} | {:n_mongo_id=>"5501791e776562c990000000", "limit_1"=>1}
2015-03-30 06:04:35 +0000 severity=INFO, CYPHER 4802ms MATCH (n1:`User`), (n2:`MovieOther`) WHERE (n1.uuid = {from_node_id}) AND (n2.uuid = {to_node_id}) CREATE (n1)-[r:`relates_movie`]->(n2) WITH r SET r.`relation_type` = {setter_r_relation_type}, r.`source` = {setter_r_source} RETURN r | {:from_node_id=>"b7763aa5-1949-4bce-98ee-8b475e1870a1", :to_node_id=>"d142c6cd-5aec-43de-9d28-f6d9ff160a2b", :setter_r_relation_type=>"watched", :setter_r_source=>"facebook"}
`````

**Comment by subvertallchris** [comment] 2015-03-30 12:51
That looks like a timeout. Lock your gemfile to the most recent commits of
neo4j and neo4j-core -- don't use master, use the most recent commits and
update occasionally when Travis shows Ruby 2.2.1 is stable. Make sure
you're using Ruby 2.2.1 everywhere.

Are the first and third query in your log from ActiveRel?

**Comment by sahin** [comment] 2015-03-30 16:42
@subvertallchris I am using last stable version. 

yep they are from ActiveRel.

I have global way to add activerel like this.

```
  rel = "Neo::Relations::#{rel_klass}".constantize.new(from_node: self, to_node: to_node)
    rel_params.keys.each do |key|
      rel.send(key.to_s + '=', rel_params[key])
    end
    rel.save!
```

an example
```
module Neo::Relations
  class MovieOther
    include Neo4j::ActiveRel

    from_class Neo::User
    to_class   Neo::MovieOther

    type 'relates_movie'

    property :relation_type
    property :source,  presence: true

    validates_presence_of :relation_type
    validates_inclusion_of :relation_type, in: %w{watched wants-to-watch likes}

    validates_inclusion_of :source, in: %w{facebook}
  end
end
```

**Comment by subvertallchris** [comment] 2015-03-30 17:02
https://github.com/neo4jrb/neo4j/commit/25cec5464ccba408467842852c739415f9c41aad improves ActiveRel performance by using neo_id to create relationships instead of uuid and skips a label check. It's not released yet, though, so you'll need to lock at that commit to get the update.

Do you have a lot of workers starting up throughout the day? If so, https://github.com/neo4jrb/neo4j/commit/7c1afdedffd15dc1ed353a639ba2246b021ca6e7 will help your performance a lot.

Both of these depend on https://github.com/neo4jrb/neo4j-core/commit/5c70da6a5eddaab51ff23b8b492657aabb662da4.

**Comment by sahin** [comment] 2015-03-30 19:01
I can move to master and try ...

I will check the cache size, this cache size in neo4j is super annoying compare any other database. 

We have a lot of workers, but right now, there is only 10 workers at the same time...

**Comment by sahin** [comment] 2015-04-01 05:43
@subvertallchris I moved to neo4j master and neo4j-core master. it definitely improve. 

There is no java people in @movielala so I am moving to graphstory.com, I will tell u performance. 

Btw,  graphstory.com neography in their doc, I reached to them and send the init code for neo4jrb to add to their docs :)

    require 'neo4j/railtie'

     config.neo4j.session_path = 'https://xxxx:x@neo-xx-x.do-stories.graphstory.com:7473'
      config.neo4j.session_options = {
          initialize: {
              request: {
                  open_timeout: 2,   # opening a connection
                  timeout: 120       # waiting for response
              }
          }
      }
    config.neo4j[:cache_class_names] = true #improves Cypher performance
    config.neo4j.session_type = :server_db

    puts "connecting #{config.neo4j.session_path}"

**Comment by subvertallchris** [comment] 2016-01-17 02:23
This is typically related to performance issues on the server and hasn't been seen in ages, so I'm going to close the issue.

**Closed by subvertallchris** 2016-01-17 02:23 UTC

**Comment by cheerfulstoic** [comment] 2017-03-25 14:39
We were seeing this issue in tests / production.  I recently added some functionality to `neo4j-core` to allow configuring of different adaptors and that allowed us to switch to `typhoeus` which so far has been more stable (it's ever so slightly slower, but we decided that not getting these errors was definitely worth it).  So if anybody is experiencing this make sure you're on at least `neo4j-core` 7.0.8 and check out the docs:

http://neo4jrb.readthedocs.io/en/8.0.x/Setup.html#configuring-faraday

Example configuration here as well:

```ruby
config.neo4j.session.options = {
  faraday_configurator: proc do |faraday|
    faraday.adapter :typhoeus
  end
}
```

If you are using the `neo4j-core` gem directly (rather than `neo4j`) you can do:

```ruby
faraday_configurator = proc do |faraday|
  faraday.adapter :typhoeus
end
http_adaptor = Neo4j::Core::CypherSession::Adaptors::HTTP.new('http://neo4j:pass@localhost:7474', faraday_configurator: faraday_configurator)
```

**Comment by cheerfulstoic** [comment] 2017-03-25 14:39
If `typhoeus` is continues working well for us at work for another 2-3 months I'll likely switch the default adaptor inside of `neo4j-core` to `typhoeus`
