### ISSUE TITLE
Unique, non case sensitive properties breaking in master

### ISSUE THREAD

**Issue by LouisSayers** [neo4jrb/neo4j#963] opened 2015-09-14 04:37 UTC
I've discovered an issue currently on master to do with non case-sensitive unique properties. Looks like it works fine on v5.2.5.

Here's a test to confirm (pass on v5.2.5, but breaking on master):

```Ruby
require 'spec_helper'

describe 'unique properties' do
  describe 'non case-sensitive property' do
    before do
      clazz = Class.new do
        include Neo4j::ActiveNode
        property :unique_property, type: String, constraint: :unique

        validates :unique_property, uniqueness: { case_sensitive: false }
      end
      stub_const('MyClass', clazz)
    end


    context 'invalid model' do
      let(:property_value) { 'some-value' }
      let(:obj_with_unique_value) { MyClass.new(unique_property: property_value) }
      let(:obj_with_same_value)   { MyClass.new(unique_property: property_value) }
      let(:error_msg) { 'translation missing: en.neo4j.errors.models.my_class.attributes.unique_property.taken' }

      subject { obj_with_same_value }

      before { obj_with_unique_value.save }

      it { is_expected.not_to be_valid }

      it 'has an error message' do
        subject.save
        expect(subject.errors[:unique_property]).to eq [error_msg]
      end
    end
  end
end
```

**Comment by cheerfulstoic** [comment] 2015-09-14 05:44
Interesting, thanks for reporting this!

I'm looking at it now.  The first thing I see is that a `Neo4j::Server::CypherResponse::ConstraintViolationError` gets raised on the second save.  That makes sense to me because the constraint would have Neo4j enforce the uniqueness so I'm not sure how your tests gets past that to check for an error.

I've made a spec which is somewhat different but should do the same thing.  I'm also testing for values with the same value with different cases and that is failing on both 5.2.x and master.

**Comment by cheerfulstoic** [comment] 2015-09-14 05:51
Ah, I think I see.  The validation checks the database before the create so it shouldn't even get to Neo4j to complain.  I'm not sure why I got the constraint error.  But I seem to be able to reproduce it now.  I'm taking a look

**Comment by cheerfulstoic** [comment] 2015-09-14 05:54
Looks like it's because the regular expression sent down changed:

5.2.x
```
 CYPHER 5ms MATCH (result:`Uniqueness`) WHERE (result.unique_property =~ {result_unique_property}) RETURN COUNT(result) AS count | {:result_unique_property=>"(?i)^test$"}
```

master
```
 CYPHER 8ms MATCH (result:`Uniqueness`) WHERE (result.unique_property = {result_unique_property}) RETURN COUNT(result) AS count | {:result_unique_property=>"(?i-mx:^test$)"}
```

**Comment by LouisSayers** [comment] 2015-09-14 06:02
thanks for looking into it so quickly! :+1:

**Comment by cheerfulstoic** [comment] 2015-09-14 09:08
I think that'll fix it.  Could you try pulling master and giving it a go?

FYI to @subvertallchris I think that this was from commit 00629aae8be582366a8b8bb855516fd033eabfbd.  The regular expressions being passed down were getting `to_s` called on them and thus when it was getting down to `neo4j-core` it was no longer a Regexp and couldn't be converted to the Cypher `=~` / regexp syntax.  My fix (along with other fixes) is here: https://github.com/neo4jrb/neo4j/commit/36dd768840a8f313135e23b079da1fdc12e52220

**Comment by subvertallchris** [comment] 2015-09-14 11:39
Nope, not that commit. The String converter was added and QueryProxy was made aware of it in #959.

**Comment by subvertallchris** [comment] 2015-09-14 11:41
And in fact, this just made me aware of another bug that this will cause... Incoming commit similar to what you just did for Regex.

**Comment by subvertallchris** [comment] 2015-09-14 16:11
Try pulling from master again, if you don't mind. It won't change the behavior of what Brian fixed but it will fix potential issues with Range and Array.

**Comment by subvertallchris** [comment] 2015-10-09 14:36
Going to close this since it's been part of a release, but let us know if you have any more trouble.

**Closed by subvertallchris** 2015-10-09 14:36 UTC
