### ISSUE TITLE
Uniqueness on has_many relations

### ISSUE THREAD

**Issue by raphi** [neo4jrb/neo4j#856] opened 2015-07-03 19:28 UTC
When you have a has_many relation like this:
```has_many :out, :likes, type: :LIKES, model_class: User, unique: true```

How do you validates uniqueness?
Currently it's raising a CypherError like:
```Neo4j::Session::CypherError - The pattern (start)-[`rel1`:`LIKES`]->(end) produced multiple possible paths, and that is not allowed: [...]```

**Comment by subvertallchris** [comment] 2015-07-03 19:29
I've never encountered that one. When does that error occur?

**Comment by raphi** [comment] 2015-07-03 21:05
Yes that's the issue. One a property, we can add a constraint unique and then add a validation on it.
Example:
```
  property :name, type: String, constraint: :unique
  validates_uniqueness_of :name, case_sensitive: false
```

Is it possible to do the same but for a relation?

**Comment by subvertallchris** [comment] 2015-07-03 21:12
No, it is not, the validations on ActiveNode models are only for the nodes managed by the model.

If you want relationship validations, can use ActiveRel models, but you won't be able to use builtin validators like `validates_uniqueness_of` there, either. You could create a custom validator to ensure that the `from_node` and `to_node` satisfy custom requirements, though.

If you haven't already, you also might want to read [this](https://github.com/neo4jrb/neo4j/wiki/Validation-and-Case-Sensitivity-in-Neo4j.rb-3.0) post in the wiki regarding case sensitivity and constraits.

**Comment by raphi** [comment] 2015-07-04 08:10
I see. Would you recommend to let Cypher raise the constraint error and catch it or to run a query first that check if the relationship already exists?

**Comment by subvertallchris** [comment] 2015-09-11 00:50
Hi @raphi, sorry for not responding to your question here. The Cypher constraint error will be more authoritative in the sense that it will be impossible for it to fail but the validation _feels_ better to me from a Rails workflow perspective. You could do both, relying on the database constraint to catch something that does make it through just to be totally sure, if you want the best of both worlds.

Incidentally, shortly after you posted this, I did run into this error. It's caused by already having multiple instances of the relationship in place and then trying to use `CREATE UNIQUE`.

```ruby
# If we assume that both :likes and :unique likes use the same relationship type but `unique_likes` has `unique: true` set...

user.likes << user2
user.likes << user2
user.unique_likes << user 2
# will return your error
```

You probably have an association somewhere that doesn't have `unique: true` set. We ran into it where I was working in places where ActiveNode associations did not have it set but an ActiveRel class did. The gem has since been modified so associations will use the uniqueness specified in the association.

I'm going to close this issue, but please let me know if you have any questions or problems.

**Closed by subvertallchris** 2015-09-11 00:50 UTC

**Comment by raphi** [comment] 2015-09-11 09:09
Very clear thanks :+1:
