### ISSUE TITLE
no uuid created when creating a node

### ISSUE THREAD

**Issue by angelacode** [neo4jrb/neo4j#1373] opened 2017-04-21 06:13 UTC
http://stackoverflow.com/questions/43535208/neo4j-uuid-is-not-created

Additional information which could be helpful if relevant to your issue:

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.0
`neo4j-core` gem version:

**Comment by angelacode** [comment] 2017-04-21 06:20
RuntimeError: No session defined!
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13/lib/neo4j/active_base.rb:9:in `block in current_session'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13/lib/neo4j/active_base.rb:8:in `tap'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13/lib/neo4j/active_base.rb:8:in `current_session'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13/lib/neo4j/model_schema.rb:35:in `model_constraints'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/neo4j-8.0.13/lib/neo4j/model_schema.rb:131:in `each_schema_element'

**Comment by cheerfulstoic** [comment] 2017-04-21 13:03
I just answered on StackOverflow (note for anybody else coming along there was also [this question](http://stackoverflow.com/questions/43535082/neo4j-runtimeerror-no-session-defined/43543442#43543442) )

**Comment by cheerfulstoic** [comment] 2017-04-22 03:22
Closing because I think it's configuration, not a bug, so SO is more appropriate

**Closed by cheerfulstoic** 2017-04-22 03:22 UTC
