### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by anamba** [neo4jrb/neo4j#1496] opened 2018-04-09 08:21 UTC
Just curious where there's any progress on Rails 5.2 support, maybe a branch I can try?

I tried out neo4jrb + 5.2 briefly when rc1 came out, and again for rc2, but it is sadly still unusable. I tried cloning this repo and running the specs to see if there might be some kind of quick and easy fix, but I get thousands of spec failures, most of which are either `NoMethodError: undefined method 'changed?' for nil:NilClass` or `Neo.ClientError.Transaction.TransactionNotFound: Unrecognized transaction id. Transaction may have timed out and been rolled back.` It seems like something is amiss with constraints, but it doesn't seem to be something obvious enough for me to be able to fix on my own...

**Comment by cheerfulstoic** [comment] 2018-04-09 20:47
@anamba Thanks for the report!

I've not been trying the Neo4j.rb gems with Rails 5.2 and haven't seen any reports yet, so any information that you can provide would be helpful.  Could you provide a full backtrace for the error(s) you are getting and perhaps some sample code for an example of where it's occurring?

If you don't want to post your code publicly you could share a private gist URL with me via the form on the [Neo4j.rb homepage](http://neo4jrb.io/)

Thanks again

**Comment by anamba** [comment] 2018-04-09 23:24
Here's what I did yesterday to check for Rails 5.2 support (if I did it today it would be different, since 5.2.0 is out now).

First, I cloned this repo, did a `bundle install` and `rspec`. Bundler installed activemodel/activesupport/railties 5.1.6 and all specs passed. (If I did this now, it would install 5.2.0).

Next, I updated neo4j.gemspec to specify 5.2.0.rc2 for activemodel/activesupport/railties and ran `bundle update`, then ran `rspec` again. This time, most of the specs failed (`1601 examples, 1224 failures, 2 pending`).

**Comment by cheerfulstoic** [comment] 2018-04-10 00:24
Hrmm, you shouldn't need to check out the repo and change the `gemspec`.  Do you mean that you ran the tests inside of the `neo4j` gem repo, or the tests inside of your project pointing to your checked out repo?

The `neo4j.gemspec` file is what helps build the gem for people to use.  So the `activemodel` and `activesupport` dependencies inside of the `neo4j.gemspec` should stay as `'>= 4.0'` because that means that the `neo4j` gem will require at least version 4.0.0 of those gems but it will also support version 5.x.y, 6.x.y, etc... (though, of course, we don't know if there will be problems with Rails 6.0 until it comes out).

If you're trying to run the tests in this repo locally (and I'll try to do this now), the `neo4j.gemspec` should stay the same and you should do `bundle update activemodel activerecord` to see if the gem is compatible with the latest versions of those gems (the `Gemfile` has a `gemspec` declaration which causes it to use the dependencies from the `neo4j.gemspec` file and the `Gemfile.lock` will hold whatever specific version of the gem you're trying to use right now)

**Comment by cheerfulstoic** [comment] 2018-04-10 00:27
Oh, also, if you're running the `neo4j` repo specs, you'll need to have a version of Neo4j running and a `NEO4J_URL` environment variable set to point to it (beware that it will wipe the database, including indexes and constraints)

**Comment by cheerfulstoic** [comment] 2018-04-10 00:29
Looks like you need to run `bundle update activemodel activesupport railties` because `railties` is tied up in there too

**Comment by cheerfulstoic** [comment] 2018-04-10 00:33
Wow, ok, after all that I can confirm that it's working for me in 5.1.x but not 5.2.x.  I'll take a look, thanks ;)

**Comment by cheerfulstoic** [comment] 2018-04-10 00:59
Yup, failing on CI too.  I just re-ran one of the tasks now that 5.2.0 is out (CI will automatically pull in the latest):

https://travis-ci.org/neo4jrb/neo4j/jobs/360924370

**Comment by cheerfulstoic** [comment] 2018-04-10 01:46
😞 it looks like `activemodel` 5.2 refactors attributes, either to use something new or to use something that was already there.  But I think that some of the creakier parts of the `ActiveNode` code are breaking with the change.  I made [a branch](https://github.com/neo4jrb/neo4j/tree/rails_5_2) with some of the fixes that I've made so far.  Currently the problem is that it doesn't seem to like it when you assign things to the underlying `@attributes` instance variable that aren't objects like `ActiveModel::Attribute::FromUser` or `ActiveModel::Attribute::FromDatabase` and the code is just assigning a string for the `uuid`.  This also goes to the fact that there have been various requests to make the default `uuid` `id_property` just an attribute like everything else, so now might be a good time.  But it would probably take some time and some refactoring.  I need to cut out for now, though.

**Comment by anamba** [comment] 2018-04-12 05:33
Happy to help test once you've got something semi-working. Would love to help fix things as well, but I am still relatively new to neo4jrb and neo4j in general. (One of these days, though, you can look forward to getting a pull request from me.)

**Comment by aledalgrande** [comment] 2018-04-15 22:42
As Rails 5.2 is now out, would be great to get this fixed. 🙇

**Comment by cheerfulstoic** [comment] 2018-04-16 11:46
@aledalgrande This is certainly my highest priority, but it's probably not going to be simple and I can can only work on it in my spare time.  I've updated the `README` to warn people in the meantime, though

**Comment by cheerfulstoic** [comment] 2018-04-16 12:38
@anamba Thanks very much!  Normally I'd suggest jumping in, but this bit of code is kind of hairy.  Just got back from holiday, but I'll hopefully soon see if I can scope it

**Comment by subvertallchris** [comment] 2018-04-16 21:30
I’ve got a branch with passing specs. The changes were pretty simple,
though I’d appreciate careful review. We will probably need to implement
some methods to fill in gaps for compatibility with old Rails, too. I have
no internet other than email but I’ll push it up tonight and you guys can
kick the tires.

**Comment by cheerfulstoic** [comment] 2018-04-17 00:51
Yeah, I know there's definitely some things that seemed like they might not be backwards compatible, but I'm looking forward to seeing the changes!  Thanks!

**Comment by cheerfulstoic** [comment] 2018-04-18 13:16
FYI for anybody following, check out this PR:

https://github.com/neo4jrb/neo4j/pull/1499

I think it's most of the way there, but CI is taking a long time to run every time we make changes.  I think it's mostly working for ActiveModel 5.2, but the tests are failing for Ruby 2.1 (which may be because newer versions of Rails require Ruby 2.4, IIRC, though I'm not sure).  Also, I added a build on CI for `ActiveModel` 5.1 (since CI uses the most recent version by default), so we need to see how that runs.  When I ran it locally I think I saw problems

**Comment by aledalgrande** [comment] 2018-04-18 17:58
Rails requires Ruby 2.2.2 since 5.1 https://rubygems.org/gems/rails/versions/5.1.4

**Comment by cheerfulstoic** [comment] 2018-04-20 01:14
The fix from #1499 has been released as version 9.2.2 of the gem.  Give it a try!

**Comment by anamba** [comment] 2018-04-24 05:37
9.2.2 is doing everything I need it to so far. Thanks!

**Comment by cheerfulstoic** [comment] 2018-04-24 12:54
🎉 Thanks for the feedback!

**Closed by cheerfulstoic** 2018-04-24 12:54 UTC
Labels: in progress

**Comment by subvertallchris** [comment] 2018-04-24 13:16
🎉🤘🎉
