### ISSUE TITLE
error on signing out

### ISSUE THREAD

**Issue by artsince** [neo4jrb/neo4j#775] opened 2015-05-01 17:33 UTC
I am getting the following stack trace when I try to sign out. Signing out is handled by devise gem, without any customizations.

I am running into this problem in my own development computer as well as in our server both running on ubuntu 14.04. However, I don't get into this error on OSX (yosemite)

Thanks a lot,
ahmet

```
NoMethodError - undefined method `year' for nil:NilClass:
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:32:in `to_db'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:160:in `to_other'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:122:in `converted_property'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:115:in `block in convert_properties_to'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:113:in `each'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:113:in `each_with_object'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/type_converters.rb:113:in `convert_properties_to'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/persistence.rb:12:in `update_model'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/callbacks.rb:46:in `block (2 levels) in update_model'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_update_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/callbacks.rb:46:in `block in update_model'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-core-4c274bd09e62/lib/neo4j/transaction.rb:83:in `run'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/callbacks.rb:45:in `update_model'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/persistence.rb:36:in `create_or_update'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/active_node/persistence.rb:27:in `save'
   () home/ahmetkizilay/.rvm/gems/ruby-2.1.2/bundler/gems/neo4j-74cfdb580288/lib/neo4j/shared/validations.rb:18:in `save'
  devise (3.4.1) lib/devise/models/rememberable.rb:62:in `forget_me!'
  devise (3.4.1) lib/devise/controllers/rememberable.rb:23:in `forget_me'
  devise (3.4.1) lib/devise/hooks/forgetable.rb:7:in `block in <top (required)>'
  warden (1.2.3) lib/warden/hooks.rb:14:in `call'
  warden (1.2.3) lib/warden/hooks.rb:14:in `block in _run_callbacks'
  warden (1.2.3) lib/warden/hooks.rb:9:in `each'
  warden (1.2.3) lib/warden/hooks.rb:9:in `_run_callbacks'
  warden (1.2.3) lib/warden/manager.rb:53:in `_run_callbacks'
  warden (1.2.3) lib/warden/proxy.rb:262:in `block in logout'
  warden (1.2.3) lib/warden/proxy.rb:260:in `each'
  warden (1.2.3) lib/warden/proxy.rb:260:in `logout'
  devise (3.4.1) lib/devise/controllers/sign_in_out.rb:75:in `sign_out_all_scopes'
  devise (3.4.1) lib/devise/controllers/sign_in_out.rb:57:in `sign_out'
  devise (3.4.1) app/controllers/devise/sessions_controller.rb:25:in `destroy'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

```

**Comment by artsince** [comment] 2015-05-01 18:12
I investigated the error a little further. I can trace the error back to `convert_properties_to` method [shared/type_converters])https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/type_converters.rb#L110)

The error seems to come from the `remember_created_at` attribute whose value is `nil`. Here's the print out of the properties:
> {"updated_at"=>Fri, 01 May 2015 14:03:28 -0400, "remember_created_at"=>nil}

thanks

**Comment by subvertallchris** [comment] 2015-05-01 18:14
It's having trouble setting a time stamp, it expects one where none
exists. Are you working off of the master branch of neo4j? Did it ever work?

Maybe see if you can figure out what it's looking for, why it's not there.
We should run the neo4j-devise specs against master, too. (You are using
that gem, too, right?)

**Comment by artsince** [comment] 2015-05-01 18:22
@subvertallchris I think it is specifically looking for `remember_created_at` which is nil. 

I am using neo4j-74cfdb580288

I am using devise-neo4j too.

here is the partial console output from bundle install
```
Using neo4j-core 4.0.1 from https://github.com/neo4jrb/neo4j-core (at master)
Using neo4j 4.1.2 from https://github.com/neo4jrb/neo4j (at master)
Using devise-neo4j 2.0.0
```

**Comment by subvertallchris** [comment] 2015-05-01 18:37
I'm not at a computer, is that the most recent commit? If so, try rolling
back a few. I've been refactoring initialization and property management
methods for speed and I wonder if there's a condition that we're not
testing.

**Comment by artsince** [comment] 2015-05-01 18:40
Here's the commit: https://github.com/neo4jrb/neo4j/commit/74cfdb580288
on march 12, not the most recent commit.

**Comment by artsince** [comment] 2015-05-04 16:11
@subvertallchris do you think the reason for the error is that the converter thinks `remember_created_at` as DateTime whereas it is actually a boolean?

**Comment by arikan** [comment] 2015-05-15 02:41
Getting the exact same error, while signing out, resetting password etc. it is caused by certain Devise related actions:

```
NoMethodError - undefined method `year' for nil:NilClass:
```

devise (3.4.1)
devise-neo4j (2.0.0)
neo4j (4.1.2)
neo4j-core (4.0.1)
rails 4.2.0 

Could it be what @artsince says, the converter expects `remember_created_at` as DateTime whereas it is a boolean?

**Comment by artsince** [comment] 2015-05-15 05:10
I did some more research on this issue. Now I am sure that the error is caused by `remember_created_at` being nil.

`remember_created_at` is set to nil in the `forget_me` method of the devise gem:  [link](https://github.com/plataformatec/devise/blob/master/lib/devise/models/rememberable.rb#L61)

which causes neo4j gem to throw exception [here](https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/shared/type_converters.rb#L32):

to confirm, I added this unit test to `type_converters_spec.rb` and I get the same error:
```rb
    it 'translate from and to database when value is nil' do
      value = nil
      db_value = Neo4j::Shared::TypeConverters::DateTimeConverter.to_db(value)
      ruby_value = Neo4j::Shared::TypeConverters::DateTimeConverter.to_ruby(db_value)
      ruby_value.class.should eq(DateTime)
      ruby_value.to_s.should eq(value.to_s)
    end
```

I attempted to modify the `to_db` method for a work around when value is nil
1. I add `fail ArgumentError, "Invalid value type for DateType property: #{value.inspect}"` to be consistent with the `to_ruby` method. but that does not really work, as the exception is not handled anywhere up the stack.
2. I simply return 0. This actually works, I can sign out without any errors. Obviously this is not a very elegant solution.

I did not try this, but it also seems possible to bypass devise gem to nullify the value by setting `expire_all_remember_me_on_sign_out` to false. see the `forget_me` link above. 

@subvertallchris what do you think is the right action to take here?

**Comment by artsince** [comment] 2015-05-15 05:29
@arikan from the devise gem, I see that `remember_created_at` is intended to be a DateTime.

**Comment by artsince** [comment] 2015-05-15 06:36
see: https://github.com/artsince/neo4j/commit/c7be8a561531ddc37477ca1e668e73023d15aea4

**Comment by subvertallchris** [comment] 2015-05-15 15:24
Hey guys, really sorry for dropping the ball on this. Been focused on work and other projects within the gem and this totally slipped my mind.

I'm having trouble reproducing the problem, everything works for me in my test app. Can you share your user models? Here's mine:

```
class User
  include Neo4j::ActiveNode

  property :first_name, type: String
  property :last_name, type: String, index: :exact
  property :age, type: Integer
  property :occupation, type: String
  property :email, type: String, constraint: :unique
  property :created_at
  property :updated_at

  [:first_name, :last_name].each { |name| validates_presence_of name }
  validates_numericality_of :age, allow_nil: true

  # Devise things
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  property :username, type:   String, constraint: :unique
  property :encrypted_password
  property :remember_created_at, type: DateTime, index: :exact

  property :reset_password_token
  index :reset_password_token
  property :reset_password_sent_at, type: DateTime

  property :sign_in_count,       type: Integer, default: 0
  property :current_sign_in_at,  type: DateTime
  property :last_sign_in_at,     type: DateTime
  property :current_sign_in_ip,  type: String
  property :last_sign_in_ip,     type: String

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  def valid_name
    "#{first_name} #{last_name}".blank? ? email : "#{first_name} #{last_name}"
  end

end
```

Rails 4.2
Neo4j and Neo4j-core gems at master
devise-neo4j at master

@artsince, I think that what you described above when testing things with TypeConverters is working as intended. The converters aren't intended to be used directly, the check for nil happens in the `convert_properties_to` method, which determines whether conversion is necessary. If a nil value does make it to a converter, you'll get an error.

**Comment by subvertallchris** [comment] 2015-05-15 15:28
Also, moving back through the comments here... If `remember_created_at` is supposed to be a Boolean, what happens if you change its type to `Boolean` in the model?

I haven't used Devise very much so please excuse any gaps in knowledge.

**Comment by artsince** [comment] 2015-05-15 17:15
@subvertallchris 
I am debugging `skip_conversion` method. it seems like this attribute is not skipped because `obj.changed_attributes[attr]` is not false.

```rb
     def skip_conversion?(obj, attr, value)
      if attr == 'remember_created_at'
        puts obj.class.attributes[attr]
        puts value.nil?
        puts obj.changed_attributes[attr]
      end
      !obj.class.attributes[attr] || (value.nil? && !obj.changed_attributes[attr])
      # !obj.class.attributes[attr] || (value.nil?)
    end
```
> remember_created_at # obj.class.attributes[attr]
> true # value.nil?
> 2015-05-15T16:48:25+00:00 # obj.changed_attributes[attr] 

removing `obj.changed_attributes[attr]` works.

**Comment by subvertallchris** [comment] 2015-05-15 21:18
I can't remember why it checks `changed_attributes` but I feel like it has something to do with changing values from set to nil... What happens when you run the Neo4j gem specs with that change made?

**Comment by artsince** [comment] 2015-05-15 21:48
@subvertallchris spec tests work without errors. 
I updated my project Gemfile to reference this new branch. I don't get the nil class error in my project anymore.

**Comment by subvertallchris** [comment] 2015-05-18 04:27
Ah! I know why it was checking `changed_attributes`. Until recently, the type conversion process created a new hash instead of modifying the existing properties in place prior to save. Because of this, it was necessary to differentiate between values that were and always had been nil and those that were going from set to nil.

Looks good to merge this in. Do you want to remove the comment in your branch and do a PR?

**Comment by artsince** [comment] 2015-05-18 06:13
@subvertallchris thanks. sent the PR #804

**Comment by subvertallchris** [comment] 2015-05-18 17:33
Just merged that in so we should be good here. Good find on that!

**Closed by subvertallchris** 2015-05-18 17:33 UTC
