### ISSUE TITLE
Boolean Defaults Not Saved

### ISSUE THREAD

**Issue by jacobwgillespie** [neo4jrb/neo4j#948] opened 2015-08-31 18:12 UTC
Boolean default values do not seem to be saved into the db when calling `Model.new(params).save` on 5.1.5.  Here's an example model:

```ruby
class User
  include Neo4j::ActiveNode
  include GlobalID::Identification

  # Properties

  property :username, type: String
  property :login, type: String
  property :email, type: String
  property :hashed_password, type: String
  property :name, type: String

  property :created_at, type: DateTime
  property :updated_at, type: DateTime

  property :is_verified, type: Boolean, default: false
  property :is_site_admin, type: Boolean, default: false
  property :is_private, type: Boolean, default: false

  property :test_default, type: String, default: 'works'
  ...
end
```

This saves the values of the boolean `is_verified`, etc., properties:

```ruby
u = User.new
u.assign_attributes(params)
u.save
```

```ruby
CYPHER 52ms CREATE (n:`User` {props}) RETURN ID(n) | {:props=>{:uuid=>"2841bba0-c4d2-4a65-864a-71e7606a27d4", :username=>"test", :login=>"test", :email=>"test@example.com", :hashed_password=>"$2a$10$xpiWg6pZabwnSAL66oxGT..zUthcRTIX8sBlQev4cphJd09euetZy", :name=>"test", :created_at=>1441043306, :updated_at=>1441043306, :is_verified=>false, :is_site_admin=>false, :is_private=>false, :test_default=>"works"}}
```

And this does not:

```ruby
u = User.new(params)
u.save
```

```ruby
CYPHER 53ms CREATE (n:`User` {props}) RETURN ID(n) | {:props=>{:uuid=>"d7fcd455-a01e-4475-84e5-a7ce0bfae36e", :username=>"test", :login=>"test", :email=>"test@example.com", :hashed_password=>"$2a$10$r6mOaJNlqez25.MG01fuuuIqR07sQXiTHY9UWEjmRQ46YaN/u8iGW", :name=>"test", :created_at=>1441043368, :updated_at=>1441043368, :test_default=>"works"}}
```

The default value of `test_default` will be saved in the DB with either.

Not sure if it matters, but `params` is the return value from `params.permit(:name, :username, ...)`.

**Comment by subvertallchris** [comment] 2015-08-31 20:28
Good catch. Are you sure it's just Boolean defaults?

The master branch, targeting 5.2.x, includes a heavy refactor of the
persistence process. Maybe try with that to see if it got corrected along
the way.

I'm on vacation right now without my computer so unfortunately won't be
able to dive into this until I return next week. I'm not sure of Brian's
workload so can't commit him to a fix... If the 5.2.0 release doesn't fix
it, can yo work around it until then?

**Comment by jacobwgillespie** [comment] 2015-09-01 02:15
Hey @subvertallchris - no rush!  Yeah, talked with @cheerfulstoic via Slack and we opened this issue just to track progress as everybody's got busy schedules for the next few days.

I'll test with 5.2.x and report back - it did seem to only be boolean (and I only tested with `default: false`, fwiw) as string defaults were being saved.  For now, yeah, working around everything. 

Cheers!

**Comment by leviwilson** [comment] 2015-09-02 14:43
I'm doing a `MyClass.merge` where `MyClass` has `property :include, type: Boolean, default: true` and the same issue is happening (`:include` is not on my node).

**Comment by subvertallchris** [comment] 2015-09-07 23:25
Hey guys, using 5.2.3, I'm unable to reproduce this. See below, please excuse nonsense property names, it's from my test app:

```ruby
2.2.2 :013 > s = Student.new(a: 'Chris')
 => #<Student uuid: nil, a: "Chris", b: nil, c: nil, d: nil, e: nil, f: nil, g: nil, h: nil, i: nil, k: nil, l: nil, m: nil, name: nil, omgwut: nil> 
2.2.2 :014 > s.save
 CYPHER 6ms CREATE (n:`Student` {props}) RETURN ID(n) | {:props=>{:uuid=>"2c4b009d-5f51-44f1-add4-02b362fb032c", :a=>"Chris", :l=>true}}
 => true 
2.2.2 :015 > s._persisted_obj.props
 => {:uuid=>"2c4b009d-5f51-44f1-add4-02b362fb032c", :a=>"Chris", :l=>true} 
2.2.2 :016 > s.l
 => true 
```

The `l` property is set to Boolean, defaults true. Can anyone verify with the latest version?

@leviwilson `merge` and `find_or_create` probably need some attention to fix this. I can modify them to use the newer persistence helpers, should clear it up.

**Comment by subvertallchris** [comment] 2015-09-08 00:52
Ha! Found it. It's actually only failing when the default is set to false because...

```
declared_property_defaults[property.name] = property.default_value if property.default_value
```

It was evaluating for _falsey_, not nil. It also revealed a problem with the way property defaults were being applied that would effect `merge` and `find_or_create`. Won't have the fix in tonight but I'll finish it up tomorrow.

**Comment by subvertallchris** [comment] 2015-09-08 18:46
Could you guys try with ref 89378a7d80a166a2208744d61607737696fe9105 ? It should fix them. I have a few other bugs to fix before a patch is released, all feedback is helpful!

**Comment by subvertallchris** [comment] 2015-09-11 00:42
This will be in 5.3.0 tomorrow.

**Comment by subvertallchris** [comment] 2015-10-13 14:47
This ended up going in the 6.0.0.alpha.1 release last night. Let us know if you have any trouble.

**Closed by subvertallchris** 2015-10-13 14:47 UTC
Labels: in master
